### ISSUE TITLE
Item Group eBay field too narrow to display full eBay Category

### ISSUE THREAD

**Issue by bglazier** [bglazier/erpnext_ebay#3]
The Item Group eBay (on Item) field is too narrow to display the full eBay Category.

Either we need to display a wider field view, which I am not sure is possible, or the eBay Category ID needs to be displayed on the View Slideshow page.

**Comment by gbm001** [comment]
Is this a high priority requirement, or should it wait until the website has been done?

**Comment by bglazier** [comment]
Not that high.  But I will add it to the View Slideshow page as a fix and then we will review if this is enough.

**Comment by bglazier** [comment]
I have amended the View Slideshow to show the Item Group.  Plus with the other option there is no requirement for the extension of the field length.
