### ISSUE TITLE
Information on running this project

### ISSUE THREAD

**Issue by kylestev** [bglazier/erpnext_ebay#31]
It wasn’t immediately apparent to me how to install this. It looks like it could be a frappe site in a bench but it is hard for me to tell and I have not been able to find any documentation on the setup process.

How are we meant to install this? Into an existing ERPNext installation as a module?

Any direction would be greatly appreciated. Thanks!

**Comment by gbm001** [comment]
Hi Kyle,

It installs in the normal ERPNext custom app way (bench install-app OPTIONS), but if you don't know how to do that then it is unlikely, unfortunately, that you will get this working. This is very much a work-in-progress; we are using it in our production server, but I don't think anyone else is using it.

We have mostly shared it in case it is useful for anyone else thinking about creating an eBay app for ERPNext.

About the only thing it does do is automatically create SINVs when you receive eBay orders. You will need to create an eBay development account and get eBay API keys etc.

It does not allow you to manage eBay listings, or create listings, or remove listings. It will create Customer and Address details and SINVs. There are probably bits of the code that are tailored to our business (even though there shouldn't be) which will need fixing before anyone else uses it. In the long run it would be nice to make this eBay app more useful, and we are planning on doing this at some point and moving away from Garagesale to direct listing, but that is probably still several years away.

**Comment by kylestev** [comment]
Just the information I was looking for. Thank you for taking the time to
reply!
