### ISSUE TITLE
There is an issue where the address is not being created for items which are unpaid

### ISSUE THREAD

**Issue by bglazier** [bglazier/erpnext_ebay#6]

**Comment by gbm001** [comment]
As I remember (from 2 years ago, so probably wrong) if they haven't paid yet it is impossible to get their address from eBay. It simply isn't accessible through the eBay API, probably for data protection reasons (you don't ever need the customer address, just a delivery address if you have a delivery to do). Strictly speaking I don't think you ever get the 'customer address' anyway, just the delivery address.

**Comment by gbm001** [comment]
Believed closed...
